### ISSUE TITLE
Apps not executed when no file is open

### ISSUE THREAD

**Issue by thorstenkampe** [liuhewei/run-app-sublime#1]
The plugin doesn't execute external apps when there is no file open in the editor. No error or indication is shown.

**Comment by liuhewei** [comment]
It's real. In my implementation, the arguments (file name, file path...) come from the opened file. So the command must be triggered within one file.
Plz check this line: https://github.com/liuhewei/run-app-sublime/blob/master/runapp.py#L8

Since RunApp is a simple plugin, I think it's suitable for most usecases.

**Comment by liuhewei** [comment]
now supported after the refactor https://github.com/liuhewei/run-app-sublime/commit/488ed52b71e9948ad75c52733b977d2dfb3d7745
